kind: pipeline
name: default
type: kubernetes

steps:
  - name: build
    image: golang:1.16
    environment:
      GOPROXY: https://registry.test4x.com/repository/go-proxy/
    commands:
      - cd cmd
      - go build
      - ls -alh
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: server
      username:
        from_secret: username
      key:
        for_secret: ssh_key
      port: 22
      source: cmd/cmd
      target: ~/gor